# Generated by Django 5.1.5 on 2025-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('horario_funcionamento', models.CharField(max_length=50)),
                ('idade_minima', models.IntegerField()),
            ],
        ),
    ]
