# Generated by Django 5.1.5 on 2025-01-29 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atracoes', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('localizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField()),
                ('Comentario', models.ManyToManyField(to='comentarios.comentario')),
                ('atracoes', models.ManyToManyField(to='atracoes.atracao')),
                ('avaliacoes', models.ManyToManyField(to='avaliacoes.avaliacao')),
                ('localizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacao.localizacao')),
            ],
        ),
    ]
