# Generated by Django 5.1.5 on 2025-01-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='localizacao',
        ),
    ]
